networks:
  internal:
    external: true
  proxy:
    external: true

services:
  freshrss:
    image: freshrss/freshrss:1
    container_name: freshrss
    restart: unless-stopped

    # ports:
    #   - "127.0.0.1:8080:80"
    
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./themes:/var/www/FreshRSS/p/themes

    env_file:
        - .env

    environment:
      TZ: ${TZ:-UTC}
      PUID: 1000
      PGID: 1000

      DB_BASE: postgres
      DB_NAME: freshrss
      DB_HOST: db
      DB_USER: ${FRSS_USER}
      DB_PASSWORD: ${FRSS_PASS}
      
      CRON_MIN: ${CROM_MIN:-2,32}

    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3

    networks:
      internal:
      proxy:
