networks:
  internal:
    external: true
    
volumes:
  postgres-data:

services:

  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    volumes:
      - ./data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d:ro

    env_file:
      - .env

    environment:
      TZ: ${TZ:-UTC}

      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: homelab
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      internal:
